name: artifact_deployed

on:
  workflow_dispatch:
    inputs:
      artifact_path:
        required: true 
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print artifact path
        run: echo  The path is ${{ inputs.artifact_path }} 
